require("config.init")
require("config.lazy")

require("config.theme")
require("config.telescope")
require("config.lualine")
require("config.treesitter")
require("config.neo-tree")
require("config.lsp")
require("config.blink")
require("config.luasnip")